spring:
  profiles:
    default: docker
  application:
    name: phonghub
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.JdbcTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info

phonghub:
  demo:
    enabled: false
